version: '2'

networks:
 prodnetwork:
  driver: bridge

services:
 mysql:
  image: mysql
  networks:
   - prodnetwork
  ports:
   - "3306:3306"
  environment:
    - 'MYSQL_ROOT_PASSWORD=password'
  volumes:
    - /var/lib/mysql

 drupal:
  image: drupal 
  networks:
   - prodnetwork
  ports:
   - 8080:80
  volumes:
    - /var/www/html/modules
    - /var/www/html/profiles
    - /var/www/html/themes
    - /var/www/html/sites
  depends_on:
    - mysql
