#
# Ansible playbook for DevOps challenge by adamkov (c)2017
#

---
- hosts: all
  become: true
  vars:
    - somevar: "somevalue"
    - somevar: "somevalue"
    - somevar: "somevalue"
  tasks:
    - name: apt-get update
      apt: update_cache=yes
      become: yes

    - name: install utils
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - wget
        - curl

    - name: install php 
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php7.0
        - php7.0-cli
        - php7.0-mbstring
        - php7.0-zip
        - php7.0-dom
        - php7.0-curl
        - php7.0-mysql
        - composer
            
    - name: install utils
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - libapache2-mod-php7.0

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: Install MySQL
      apt: name={{ item }} state=present
      with_items:
        - python-mysqldb
        - mysql-server
    - name: Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true
    - name: update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "password"
        login_user: root
        login_password: "password"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost 

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted


